### ISSUE TITLE
Boundary - rubberband restrictions so don't cross line

### ISSUE THREAD

**Issue by rgleason** [jongough/ocpn_draw_pi#11]
Possbily simplify options by restricting crossings of rubberband on previous entered lines.

**Comment by jongough** [comment]
Sounds simple, but I am not sure it is. I think there would be some quite heavy calculations as you would have to check each line for crossing another. I think this one may have to be parked until the plugin is more mature, or I have a sudden brain wave about how to do it simply. 

When editing of paths and points is working this should be less of an issue, it may still be one, but....

**Comment by rgleason** [comment]
I started thinking about this question as I was creating a boundary, and tried crossing the rubberband across a previous line segment, then I realized that my next point afterwards could undo the crossing by where I placed it.

**Comment by jongough** [comment]
Now you can right click on the boundary or a point in the boundary and move it, so you should be able to undo any crossovers that you don't want.

**Comment by rgleason** [comment]
Good point. Maybe we should close this now.  It does not seem to mess up any programming (It probably would in CAD as soon as you tried to render in 3D because the surface would be messed up, but this is not CAD and it is 2D with some projection I guess).

**Comment by jongough** [comment]
If we have a need for 3D, in the future, this will be revisited. But as you say, for 2D I would assume that non-crossing boundaries would be the norm, and putting in extra points will allow very strange shapes to be generated that should alleviate the need for crossings. But if someone comes up with a good reason why crossings need to be programmatically fixed then I will have a look.
