### ISSUE TITLE
Selection indication -  need some clue - gets dimmer, slightly larger, darker, shakes?

### ISSUE THREAD

**Issue by rgleason** [jongough/ocpn_draw_pi#12]
Need some confirmation when the cursor has selected a draw object. 
It changes in the screen somehow.
If management is open that object's line gets darker?

So there is some connection between the draw objects on the chart and the list?
Current Opencpn does not really do this so maybe it is not neccessary, but currently the only want to determine is to turn on and off show/hide OR active/inactive.

Maybe have the name show on the object?
Maybe highlight the list if the object is selected in the chart?

**Comment by jongough** [comment]
On the todo list, just haven't quite got there yet.

Will have a think about the connection between the object on the chart and the list in the manager. It may be possible to do a rollover change, i.e. when the mouse is over a line in the manager the relevant path or point could be highlighted.

At the moment there is no way to select the object on the chart. This requires right (or left) click which is not yet functioning.

**Comment by jongough** [comment]
Latest patch 0.3_0150 has shows when a path or point is selecting by flashing it using the active/inactive colours. Left and right click is working.
