### ISSUE TITLE
Text entity?

### ISSUE THREAD

**Issue by rgleason** [jongough/ocpn_draw_pi#17]
There are times when it would be nice to be able to enter text on the chart on a certain layer that could be turned off or on. For example If I want to plan a cruise or voyage, I might want to have some notes on route or ports. I am sure there are some other uses. 

I suppose this could be accomplished by using an ocpn_point and description or name that is somehow made visible and located somewhere, but I am not sure how flexible that would be.

Obviously the properties should be adjustable.

**Comment by jongough** [comment]
Yes it could by making a subclass of point which displays the description alongside the point on the chart. I have been thinking about this, but have been working on the base functionality, so have not gone anywhere with it yet.

**Comment by rgleason** [comment]
Being developed.
