### ISSUE TITLE
Building instructions for Linux.

### ISSUE THREAD

**Issue by sbfreddie** [jongough/ocpn_draw_pi#186]
Jon:
You have posted build directions for Windows, but why not for linux?  I want to build it for my ARM based board running Ubuntu 14.04.  I have already built the latest master OpenCPN and most of the plugins, but I would like to add ocpn_draw_pi to the lot.

Thanks,
Freddie

**Comment by jongough** [comment]
Freddie,
   The build for ARM is the same as the build for other unixes. You do need the build environment for OCPN on the device, then just clone the OD repository, create a new build directory, i.e build-pi, change to that directory, issue 'cmake ..', then 'make -j4' , the 'j4' just makes it run 4 compiles at the same time. If you want an install package use 'make package', if you just want to install it use 'make install'. Then just start OCPN and it should be there.

Regards
   Jon

**Comment by sbfreddie** [comment]
Jon:
Thanks,
Freddie
