### ISSUE TITLE
Updated_2 Swedish sv.po file from Crowdin

### ISSUE THREAD

**Issue by Hakansv** [jongough/ocpn_draw_pi#198]
Hi Jon
Some revisions and completion of the Swedish translations if you please.
Thanks/Håkan
[sv.po.pdf](https://github.com/jongough/ocpn_draw_pi/files/110799/sv.po.pdf)

**Comment by jongough** [comment]
Have put it in but there is an error that needs fixing. There is a new line missing.

**Comment by Hakansv** [comment]
Ok - Sorry. Now corrected in Crowdin for next "official" update of .mo 
files

Den 2016-01-31 kl. 05:09, skrev jongough:

**Comment by jongough** [comment]
Now in baseline OD
