### ISSUE TITLE
Popup menus on Right Click

### ISSUE THREAD

**Issue by jongough** [jongough/ocpn_draw_pi#2]
Following on from Dave's comment
> jon...
>
>For this one, I think it best for you to clone the relevant code into
>your PLugIn.  Watch mouse move events, draw your own popup, make your
>own timer to hide the popup later.
>
>We are trying hard to simplify the already very complex chcanv.cpp mouse
>handling stuff, and I don't want to add PlugIn callbacks unless there is
>no other way.
>
>Dont worry about the incremental requests.  This is to be expected, and
>now is a good time to add stuff to the new 1.13 API.
>
>Dave
>

 I want to be able to add items to the standard right click popup menu, so that I can add a "drop POI" or "drop OCPNPoint" marker to the list of available options. With Dave's idea I can take over the menu and replace it or display the current menu, but I cannot update its contents. I think having two actions on right click may be confusing or unusual as it would require another menu to let the user pick which menu to display.

I may be able to handle right clicking on one of the plugin objects without too many issues, but doing this on the standard canvas may be a problem. So I think there is a need to have the ability for a plugin to add line items to popup menus that can then be passed through to the plugin when selected.

Jon

**Comment by jongough** [comment]
Hmmm, submitted the above without finishing it and cannot seem to edit the content!

Anyway, I want to be able to add items to the standard right click popup menu, so that I can add a "drop POI" or "drop OCPNPoint" marker to the list of available options. With Dave's idea I can take over the menu and replace it or display the current menu, but I cannot update its contents. I think having two actions on right click may be confusing or unusual as it would require another menu to let the user pick which menu to display.

I may be able to handle right clicking on one of the plugin objects without too many issues, but doing this on the standard canvas may be a problem. So I think there is a need to have the ability for a plugin to add line items to popup menus that can then be passed through to the plugin when selected. 

Jon

**Comment by rgleason** [comment]
Is this where we select the type of object to create?  
Boundary
POI
D-point
DR Range and Bearing Line.

**Comment by jongough** [comment]
Currently the only way I have for changing the drawing type is to select the drawing icon then right click on the canvas. The pointer currently changes between a pencil (boundary/line) and a cross (point). So at the moment I will have to do the selection in a rotating manner, i.e. cycle through the available drawing types.

I am still working on getting all the basics working, still need rollover and right click to select/change. When this is done I/we can extend the drawing types to include the others you mention. 

I think, to improve the user experience, there are some more API's needed to fix up some workarounds I am using. I would like to be able to right click on the toolbar and select the drawing type to use (I think it would be more natural), but I don't want to replace the current right click menu, just extend it.

**Comment by rgleason** [comment]
I think what you have done would work fine for 3 -4 entity types.

**Comment by jongough** [comment]
Will leave the current approach for the moment until more than 4 tools are being used
