### ISSUE TITLE
please add license file

### ISSUE THREAD

**Issue by mschiff** [jongough/ocpn_draw_pi#247]
Hi,

to make the legal situation and redistribution of your code clear, please add a license file which explains under which software license you are releasing your code, thanks!

**Comment by jongough** [comment]
Each source code module has a header with the license information in it. It is following the mainline code, OpenCPN, and uses the same header information in all non-generated code. 
`
*   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
`
 
If you want to provide a license file that can be placed in the root directory please submit this as a pull request.

Thanks
Jon

**Comment by jongough** [comment]
Patch 1.4.25 has added a GPL V2 license to the OD Properties dialog box and the file is included in the distribution for viewing outside of the running application.

Can this issue now be closed?

**Comment by jongough** [comment]
Has been implemented
