### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by mbouyer** [jongough/ocpn_draw_pi#250]
Hello
I found two memory leaks in ocpn_draw_pi.cpp.
In ocpn_draw_pi::FormatDistanceAdaptive a wxString is allocated but never deleted.
In some RenderOverlay variants, an ODDC is alloctated on each call but never deleted.
The later causes my a20-based board to run out of memory after about 2 days.

I fixed the former by adding a delete call before return.
I fixed the later by removing the g_pDC global pointer and allways allocating the ODDC object on stack.
With this patch the memory usage of ocpn is stable after running for a day, while it would grow by several MB per hour before.
[patch-src_ocpn_draw_pi.cpp.txt](https://github.com/jongough/ocpn_draw_pi/files/277035/patch-src_ocpn_draw_pi.cpp.txt)

**Comment by mbouyer** [comment]
The previous patch cause a double free, because of the object copy in RenderPathLegs().
I fixed this by not using a temporary copy of the ODDC here.
Updated patch attached.
[patch-src_ocpn_draw_pi.cpp.txt](https://github.com/jongough/ocpn_draw_pi/files/277543/patch-src_ocpn_draw_pi.cpp.txt)

**Comment by jongough** [comment]
I have updated the code to put in the required 'delete' statements. Hopefully this should get rid of this memory leak. This is in patch 1.0.16, if you want to try it out and see if it solves the problem.

Thanks for the heads up.

Jon

**Comment by mbouyer** [comment]
On Mon, May 23, 2016 at 09:08:12PM -0700, jongough wrote:
> I have updated the code to put in the required 'delete' statements. Hopefully this should get rid of this memory leak. This is in patch 1.0.16, if you want to try it out and see if it solves the problem.

Hello,
I tried the last code source, and didn't notice any problem after running
for a day. So I think this indeed solves the problem.
thanks !

-- 
Manuel Bouyer <bouyer@antioche.eu.org>
     NetBSD: 26 ans d'experience feront toujours la difference
--

**Comment by jongough** [comment]
Issue fixed with patch 1.0.16
