### ISSUE TITLE
gzprop include still wrong case

### ISSUE THREAD

**Issue by seandepagnier** [jongough/ocpn_draw_pi#256]
include/wxcurl/include -I/home/sean/build/plugins/ocpn_draw_pi/ocpnsrc/lz4 -I/home/sean/build/plugins/ocpn_draw_pi/ocpnsrc/bitmaps -I/home/sean/build/plugins/ocpn_draw_pi/src/tinyxml    -Wall -fexceptions -o CMakeFiles/ocpn_draw_pi.dir/src/ocpn_draw_pi.cpp.o -c /home/sean/build/plugins/ocpn_draw_pi/src/ocpn_draw_pi.cpp
/home/sean/build/plugins/ocpn_draw_pi/src/ocpn_draw_pi.cpp:46:20: fatal error: GZprop.h: No such file or directory
 #include "GZprop.h"
                    ^
compilation terminated.
CMakeFiles/ocpn_draw_pi.dir/build.make:57: recipe for target 'CMakeFiles/ocpn_draw_pi.dir/src/ocpn_draw_pi.cpp.o' failed
make[2]: *** [CMakeFiles/ocpn_draw_pi.dir/src/ocpn_draw_pi.cpp.o] Error 1
make[2]: Leaving directory '/home/sean/build/plugins/ocpn_draw_pi/build'
CMakeFiles/Makefile2:156: recipe for target 'CMakeFiles/ocpn_draw_pi.dir/all' failed
make[1]: *** [CMakeFiles/ocpn_draw_pi.dir/all] Error 2
make[1]: Leaving directory '/home/sean/build/plugins/ocpn_draw_pi/build'
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jongough** [comment]
I have looked in the release_1.1 branch of this repository and the line is correct. This was reported a little while ago but has been fixed. Please update your version of the repository with the latest level, 1.1.14, and retry.

**Comment by seandepagnier** [comment]
I just pulled your master branch and I have from git log:

commit a9e565071bc028644de002dc6bb932707eda84af
Merge: d2e39b0 e6164cf
Author: jongough <jon.gough@eclipsesystems.com.au>
Date:   Tue Jun 7 08:22:43 2016 +1000

    Merge pull request #254 from jongough/release_1.1

    Fix a couple of windows build issues.

commit e6164cfaec08bb6c9ee75aca261dfbdf9fc949fb
Author: Jon Gough <jon.gough@eclipsesystems.com.au>
Date:   Tue Jun 7 08:20:38 2016 +1000

    Fix a couple of windows build issues.

**Comment by jongough** [comment]
I have reverted the master back to the correct location so that it does not contain any of the new code (I made a mistake and merged some of the new code with master). So now, master should build and will be at 1.0.17 and release_1.1 will be at 1.1.14

**Comment by rgleason** [comment]
Maybe this can be closed?
