### ISSUE TITLE
Degree entry into GZ

### ISSUE THREAD

**Issue by rgleason** [jongough/ocpn_draw_pi#258]
![gz-forward-anglesentry](https://cloud.githubusercontent.com/assets/2363959/16176987/75138172-35ed-11e6-8c06-b3e19bc82139.jpg)
Something very weird happens when I go into GZ Forward edit properties and try to set the angles exactly. If I enter -45 and 45 it shows correctly and then next time I open to edit I see -45 and -45 so I change it back to -45 and 45 and the GZ shows. Next time I edit it show -45 and -45, if I hit enter with no change, GZ disappears. I have to go back and put in -45 and 45 again. Very uncooperative action.

Later: If I hit "OK" to close properties, GZ disappears, If I hit "Cancel" it does not.

**Comment by jongough** [comment]
Rick, 
   On Linux it works as expected. I have just tried on windows and it gets the errors. I am looking into it.

Jon

**Comment by rgleason** [comment]
Some little format issue again.
Sorry.

**Comment by jongough** [comment]
I found a typo in the windows (non-validator) section of the code. It seems to work now. A new patch version, 1.1.18, is available that addresses this.

**Comment by rgleason** [comment]
Closing. Fixed
