### ISSUE TITLE
Watchdog Issue: Check guid to see if exist

### ISSUE THREAD

**Issue by rgleason** [jongough/ocpn_draw_pi#259]
WatchDog first needs to check if OD objects exist and if they do not exist there should be a message or something and maybe change that Alarm to Purple color.

I just ran a previous test with Watchdog with some alarms in it that I had set up, but the OD objects were deleted. Watchdog simple accepts the OD objects and sits there looking with no heads up message that the OD objects do not exist.

The objects were several guard zones that I had set up with the ship.

PS: When I go into the Alarm GUID field it does have a popup message that says the guid does not exist.
However if someone has set up guard zones previously and expects them to be there (but they've been deleted or something) when they start Watchdog, perhaps there should be some checking first to alert if there are any Guid's missing.

Small procedural detail with big consequences. - Granted this is pre-release testing of concept code.

Amendment: I think the Watchdog Alarm checkbox should be unchecked and the Alarm text should be changed to purple if the GUID does not exist. If the user tries to turn on the checkbox, then a message comes up "Guid does not exist"

**Comment by jongough** [comment]
This should now be working with patch 1.1.29

**Comment by rgleason** [comment]
I'm going to close this now Jon. I believe it is fixed.
