### ISSUE TITLE
Watchdog Issue: New Boundary Alarm, paste GUID --> bomb O

### ISSUE THREAD

**Issue by rgleason** [jongough/ocpn_draw_pi#260]
When I paste GUID into watchdog, O immediately bombs.
![gz paste guid](https://cloud.githubusercontent.com/assets/2363959/16176993/b3151efe-35ed-11e6-8f84-6decb77a6f25.jpg)

**Comment by rgleason** [comment]
Actually I don't believe this is a watchdog issue. I think the GZ Forward is malformed, because when I paste GUID into Watchdog to make a new Alarm,  O bombs. It is happened 3 times.

![gz-forward-bombed-again-on-paste-guid-to-wd](https://cloud.githubusercontent.com/assets/2363959/16177038/90ff99aa-35ef-11e6-8896-0fc892fa06a7.jpg)

I am using Hakeford-Sweden.txt
[Hakefjord-Sweden.txt](https://github.com/jongough/ocpn_draw_pi/files/322271/Hakefjord-Sweden.txt)

I am going to try to attach ODnavobj.xml







[ODnavobj.changes.docx](https://github.com/jongough/ocpn_draw_pi/files/322272/ODnavobj.changes.docx)
[ODnavobj-xml.docx](https://github.com/jongough/ocpn_draw_pi/files/322274/ODnavobj-xml.docx)
![gz-rotate-with-boat](https://cloud.githubusercontent.com/assets/2363959/16177067/6389343a-35f0-11e6-8e4f-5b8a9f6adc11.jpg)

**Comment by rgleason** [comment]
This one.
https://github.com/jongough/ocpn_draw_pi/issues/258

**Comment by rgleason** [comment]
Jon, We're going sailing today. First time this year, will be gone several days. May get some wifi, don't know. Hope this helps.

PS: I get the chuckles at how good this plugin and Watchdog are!  GZ is going to work great! It is absolutely awesome!  Great work. Thanks so much.

I hope others will help test.

**Comment by jongough** [comment]
You should be able to paste into the fields with patch 1.1.29. I have tried this under windows and linux and it all seems to work for me. If you still have the problem can you work out what you have to do to reliably recreate it? Thanks.

**Comment by rgleason** [comment]
Thanks, paste seems to be working now.
