### ISSUE TITLE
Hide ODpoints for GuardZone -when VDR is running -skews GZ when check/uncheck show ODpoint then hit "OK".

### ISSUE THREAD

**Issue by rgleason** [jongough/ocpn_draw_pi#261]
Jon, 
I figured the problem out.  
When turning off the visibility of ODpoints in a GZ when VDR is running and the GZ is rotating with the boat,  between the point when you select  ODpoint Properties and when you select Extended  and actually click on/off  "Show on Chart"  and actually hit "OK" the boat has moved and the ODpoint is not moving, so the GZ gets changed!

This causes the GZ to get distorted.

**Comment by jongough** [comment]
I think patch 1.1.26 fixes that. Although immediately after closing the GZ Point properties panel the zone may look weird it will be fixed on the next redraw. I am not sure we should be changing the position of the GZ points whilst they are being updated automatically to remain relative to the boat. That should be done through the GZ properties using the distance and angle.

**Comment by rgleason** [comment]
I agree that they should not be changed, but I am just turning off/on the "VISIBILITY" NOT moving any "POSITION"!     Therefore there should be NO disruption to the proper location, I would think.

I would even go so far as say that ODpoints Properties should be inaccessible when the boat is moving! 
That should take care of it.   Then if there were an overall ODpoint  "Hide/Visible" button within the parent GuardZone, it would perhaps help?

**Comment by rgleason** [comment]
I even wonder why people would want to see and use ODpoints in a GuardZone as long as you can edit and modify the guardzone (ie right-click on the corners and set to yellow to move (only when the guardzon is not "moving")  or right-click and pick Properties etc.  - I don't know if that approach would help avoid some of the problems, but it might.

**Comment by jongough** [comment]
I have tried to leave all the functionality that is there available. I don't want to second guess what users 'may' want to do. I would agree that playing with the ODPoints in a GZ does not make much sense, but......
I think it now works OK.

**Comment by rgleason** [comment]
This works much better.  I tried hiding a ODpoint on a GZ then showing it.
Then tried moving a ODpoint and it all worked
all while running a VDR file with GZ to follow heading!

I am going to close this now. Thanks Jon
