### ISSUE TITLE
GZ is not saved if Persistant over crash is checked.

### ISSUE THREAD

**Issue by rgleason** [jongough/ocpn_draw_pi#262]

**Comment by rgleason** [comment]
If  check Persistant over crash is checked, the GZ is not saved.

**Comment by jongough** [comment]
Patch 1.1.27 should fix this

**Comment by rgleason** [comment]
Just a question here, so I understand.
Persistent is checked and the object is saved during a crash and other times?
Persistent over crash  the object is only saved during a crash?  Not other times?

**Comment by jongough** [comment]
Persistent: Saved over normal restart and 'crash'
Persistent over crash: Not saved over normal restart, saved over 'crash'
Never: Not saved over normal restart, not saved over 'crash'

Changing between the top two works, but if you change to 'Never' on a drawn object it will, currently, still be saved. I am looking into that one.

**Comment by rgleason** [comment]
Got it. Thanks. Closing
