### ISSUE TITLE
The new GZ message is causing crashes and issues entering a GUID

### ISSUE THREAD

**Issue by rgleason** [jongough/ocpn_draw_pi#263]
1. Existing Watchdog Alarm with GUID that does not exist.
2. More than one message for the same GZ alarm pops up.  - not good 
3. When you hit OK, the checkbox for the alert is turned off.  - good
4. When you try to paste a good GUID into the GZ box, Opencpn crashes every time.
5. When you try to remove thee bad GUID and save the Alarm, it works.
6. When you then try to pastee in a goodd GUID, Opencpn crashes every time.
7. The OD Guard Zones seem to survice these crashes even when GZ properties "Persistant" is selected and not "Persistant over crash"
8. Even creating a new GZ alarm, when the GUID is pasted, O freezes.

**Comment by rgleason** [comment]
PS I think this new message is a PITA and causing replicatable  problems with the plugin, entry of GUID, and multiple alerts, etc.

**Comment by jongough** [comment]
I thought you wanted the message box. If not, it is easy to take out and makes the code simpler. The original changed the colour of the message in the WD screen and unchecked the 'Active' box. So how do we inform the users that they have an alarm which is never going to fire as the GZ is no longer there?

**Comment by rgleason** [comment]
No, Jon. I was ambivalent, I did not want it to mess stuff up though. 
Actually, if you look Sean suggested it. I was just going along....with a qualifier that it work.

**Comment by rgleason** [comment]
`.. easy to take out and makes the code simpler. The original changed the colour of the message in the WD screen and unchecked the 'Active' box. 
`
--Good, keep it.

`So how do we inform the users that they have an alarm which is never going to fire as the GZ is no longer there?`

- That's why Sean suggested a message box.  Maybe it needs to be be really simple message that only checks and runs once. Once closed it does not happen again?  I don't know what messages are doing/affecting.

- Or perhaps a hover type message when the cursor is over the alarm? -not sure if this would work...!!

**Comment by jongough** [comment]
I found a problem when running under windows that was caused by the new ODAPI. Patch 1.1.29 should fix this. The message box should only popup once as the alarm is deactivated (and made blue). The popup should only occur if the alarm is made active again, but it will immediately turn off.

**Comment by rgleason** [comment]
This is working much better. Thank you. Closing.
