### ISSUE TITLE
Which branch to build now for Pre 1.2?

### ISSUE THREAD

**Issue by rgleason** [jongough/ocpn_draw_pi#271]
Jon,
It looks to me like master is the most current branch now? 
Should I build that for prerelease 1.2?

Also Guard Zone branch looks to be 5 ahead of master ? 
What about those?

Thanks

--
I see now
https://github.com/jongough/ocpn_draw_pi/releases

Its release  1.2    64ea0fb
https://github.com/jongough/ocpn_draw_pi/commit/63f1ed65b29cfe64f64a7b8bb4dde49fc59fa721
which is the master branch,,,

actually master branch is now  "Latest commit 56ad2f7 3 days ago"   for png files change.

**Comment by jongough** [comment]
Master is now OD 1.2 and is the current version of OD.

**Comment by rgleason** [comment]
Thanks
