### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by seaside82** [jongough/ocpn_draw_pi#3]
hi
i have been took an error "/home/ruhum23/ocpn_draw_pi/src/PathMan.cpp:26:21: fatal error: pathman.h: Böyle bir dosya ya da dizin yok" when i compile.

Says there is not any file or directory as pathman.h

**Comment by jongough** [comment]
I have fixed the error. My system uses an SMB path for the files so it is case non-sensitive, sorry about that.
Please let me know if you find any other errors and I will try and fix them quickly
Jon

**Comment by rgleason** [comment]
Thanks Jon. I'll close it.

**Comment by jongough** [comment]
Issue fixed.
