### ISSUE TITLE
Why is Draw Toolbar Menu empty - ocpn_draw_pi-1.4.24-win32.exe

### ISSUE THREAD

**Issue by rgleason** [jongough/ocpn_draw_pi#323]
I am wondering why Draw Toolbar menu is empty. It is difficult to select tools....
Have not been able to test the new features as a result.
![screenshot 20](https://user-images.githubusercontent.com/2363959/33513744-c555527e-d7ad-11e7-9295-0e7c9c65f7be.png)

**Comment by jongough** [comment]
Hi Rick,
I have just done a fresh install of 1.4.24 over the top of a fresh install of OCPN 4.8.0 having downloaded them from the OD git repository. I am using Windows 7 Enterprise running under VirtualBox 5.2 on Linux and the toolbar displays OK for me with both OpenGL and without. Looking at the screenshot you are using Windows 10 which I don't have a version of (I did, but a HDD crash lost all my VM's and I am trying to rebuild them). Is it possible for you to test on Win 7?

Regards
   Jon

**Comment by jongough** [comment]
Hi Rick,
I have just tried it on windows 10 with VS2010 redistributable and VS2015 32bit and 64bit redistributable installed. The OD Toolbar displayed as expected. I have not yet installed VS2017 as it is a HUGE download and our internet is VERY slow.

Regards
   Jon

**Comment by rgleason** [comment]
Dear Jon,
I am traveling the next two days, but will try this again. I have been using VS2013 to compile.
I will try your compile of the most recent 1.24.24.
I have been using your version of OPenCPN for awhile.  Should I switch back to v4.8.0?

I could install OpenCPN on Ann's Win7 laptop in several days.
Geez you've done a lot of installing!  How is Virtualbox working now? Smooth? I had troubles with updates 2 years ago.

As you know, I have SurfPro3 with Win10 and Inspiron XPS 15 Laptop with Win10.

**Comment by rgleason** [comment]
Whoops, that is the version I tested 1.4.24
I'll have to try it on Ann's machine in several days.

**Comment by rgleason** [comment]
I downloaded v1.4.40 using did-g appevayor tool and tried it again. It works fine now. Thank you!

Closing this.
