### ISSUE TITLE
Need to set style wxTE_PROCESS_ENTER before connecting wxTextCtrl to an event handler.

### ISSUE THREAD

**Issue by transmitterdan** [jongough/ocpn_draw_pi#326]
In ODPointPropertiesDialog.cpp several wxTextCtrl items are created:

m_textLatitude
m_textLongitude
m_textCtrlODPointArrivalRadius

Then these are connected to event handlers. But they will never generate any events because the style is 0. The style must be wxTE_PROCESS_ENTER before they can generate any event.

I have not done an exhaustive search for other similar controls so this list may be incomplete.

**Comment by jongough** [comment]
Currently the OnPositionCtlUpdated is not called by the events, it is only called when the OK button is pressed. The reason for this is that the event updates the position of the point, but if that happens then the user presses "Cancel" the original position of the point to be retained. This could be handled if this is causing issues. But at the moment there I don't see the need to reposition the point before the OK button is pressed. If there is a real need then I will update the code for it.

**Comment by transmitterdan** [comment]
Probably best then not to connect them to an event handler. As it is it causes wx message boxes to pop up when using wx V3.1. I know we are using 3.0 now but eventually we will have to go to 3.1 and then it will be a problem. So if not using the events there is no need to connect and disconnect the controls.

**Comment by jongough** [comment]
In V3.1 what does the message box say. I have not updated to this version as I am trying to keep compatible with the mainline (although I am now on 3.0.3 instead of 3.0.2, but...). If I can make changes now that will solve problems later I would prefer to do that.

**Comment by transmitterdan** [comment]
The exact message is:
"A debugging check in this application has failed."
Then a message that says:
"Must have wxTE_PROCESS_ENTER for wxEVT_TEXT_ENTER to work"

**Comment by jongough** [comment]
I have added this to patch 1.4.37. It works OK for a bounday point, but a GZ point or an ELB point will not allow the setting of the lat and long if they are moving as they will immediately be overwritten when the next update happens. This is a partial work around, but more thought may be needed if it causes issues.

**Comment by rgleason** [comment]
I wonder if this can be closed , 2 yrs old.

**Comment by jongough** [comment]
Yep. Each of the handlers is now called, just the ArrivalRadius is, at the moment, a null proceedure
