### ISSUE TITLE
For windows build the point properties dialog shows some nonsensical defaults

### ISSUE THREAD

**Issue by transmitterdan** [jongough/ocpn_draw_pi#327]
In ODPointPropertiesImpl.cpp at lines 92 is this code

```#if wxCHECK_VERSION(3,0,0)
    SetLayoutAdaptationMode(wxDIALOG_ADAPTATION_MODE_ENABLED);
#ifndef _WXMSW_
    wxFloatingPointValidator<double> dODPointRangeRingSteps(3, &m_dODPointRangeRingSteps, wxNUM_VAL_DEFAULT);
    wxFloatingPointValidator<double> dODPointArrivalRadius(3, &m_dODPointArrivalRadius, wxNUM_VAL_DEFAULT);
    dODPointRangeRingSteps.SetMin(0);
    dODPointArrivalRadius.SetMin(0);
    m_textCtrlODPointRangeRingsSteps->SetValidator( dODPointRangeRingSteps );
    m_textCtrlODPointArrivalRadius->SetValidator( dODPointArrivalRadius );
#endif // not defined _WXMSW_ 
#endif // wxCHECK_VERSION(3,0,0)
```
Thus in Windows versions the arrival radius and range ring step values end up as just random numbers. Not sure why the Windows version cannot use the code to set default value and validation.

**Comment by jongough** [comment]
Hi,
   There is an error in the code above, the check should be for __WXMSW__ (double underbar before and after the WXMSW) that allows the code to run. I have tried on my windows (win 10, VS 2017, wxWidgets 3.0.3) and the code works OK, but I do remember having issues with windows and validators, hence the code not to use them.

   The code that is not used in windows just sets the validators to ensure that only valid decimals are used, and that negative values are not allowed. It does not set the default values for the fields as this is done when the dialog is displayed. 

The updated code is in patch 1.4.35
