### ISSUE TITLE
 ocpn_draw_pi-1.4.69-win32   not work with v4.8.2

### ISSUE THREAD

**Issue by rgleason** [jongough/ocpn_draw_pi#381]
ocpn_draw_pi-1.4.69-win32.exe  installs but does not work with v4.8.2
I thought v4.8.2 was compatible with API 1.15?

Can you do me a favor and identify which is the most current version that works with v4.8.2?

Also I tried installing it into 4.99 and it does not seem to work.

I am thoroughly confused.  What is the environment you are compiling in?

Should I just compile myself?

**Comment by rgleason** [comment]
I compiled ocpn_draw_pi-1.4.65-win32  and ocpn_draw_pi-1.4.69-win32  and they both work with v4.8.2

**Comment by jongough** [comment]
I may have linked against an old ocpn lib file. All my testing is currently with 4.8.2, so I know it works, but my windows capability is only slowly coming back after my HDD died. I will try relinking OD with a new release lib file.

**Comment by rgleason** [comment]
Jon I believe you cannot link against an opencpn.lib that does not compile with MSVC+2013 and wxWidgets 3.0.2    I was using Opencpn.lib   (release v4.8.0)  below



[opencpn-4.8.0.zip](https://github.com/jongough/ocpn_draw_pi/files/1777062/opencpn-4.8.0.zip)

**Comment by rgleason** [comment]
Jon, I am going to close this now. I think we'll remember this.
