### ISSUE TITLE
API 1.15 Extension ?

### ISSUE THREAD

**Issue by rgleason** [jongough/ocpn_draw_pi#382]
Jon,
Do you think you could do this?  Would be a big improvement.

[FS#2342 - API 1.15 Lat/Long Format for waypoint copy/paste Interoperability ](https://opencpn.org/flyspray/index.php?do=details&task_id=2342)

**Comment by jongough** [comment]
I have just created a 'GetLatLonFormat' call that will return the format of the lat/lon boxes. It is currently a pull request (#1068 ) on OCPN.

Regards
   Jon

**Comment by rgleason** [comment]
Thanks Jon.  I was thinking about this, and concerned that relying only on decimal degree format, might create rounding differences when converting to another format and I was going to check that, but I see you have made the call apply to all formats!  Thanks.

SDDMFORMAT
+{
+    DEGREES_DECIMAL_MINUTES = 0,
+    DECIMAL_DEGREES,
+    DEGREES_MINUTES_SECONDS,
+    END_SDDMFORMATS.

**Comment by rgleason** [comment]
Jon,
Should I close this now?
Thanks

**Comment by rgleason** [comment]
OK Thanks. Rick

**Comment by rgleason** [comment]
https://github.com/OpenCPN/OpenCPN/pull/1068

https://github.com/OpenCPN/OpenCPN/issues/1013

**Comment by rgleason** [comment]
I have tested this feature within Ocpn_Draw and it seems to work fine.
I can easily copy Lat/Long and Paste Lat/Long.
but is that all I should be testing.?
These all tend to have the same format! 
How would I test copying to a different format?

Will this also be a feature in OpenCPN?????

Not closing yet.

**Comment by jongough** [comment]
Rick,
   This change is in the O5 beta now. But I have not implemented it into OD. I will look at that when I have the drawing issues sorted with O5 MUI.

**Comment by rgleason** [comment]
Jon should I close this now? Thanks.

**Comment by jongough** [comment]
I have not seen a problem with OD with copy/paste of Lat/Lon, but if it does rear its head there is now an API call available in OCPN.

**Comment by rgleason** [comment]
I think it is working well.
