### ISSUE TITLE
EBL  Change Lat/Long and  Paste Lat/Long do not work.

### ISSUE THREAD

**Issue by rgleason** [jongough/ocpn_draw_pi#388]
The Change lat/long and Copy/paste lat/long fixes for windows are great.

EBL is acting a little strange in this regard as the Lat/Long seems to be very persistant, even when changed.

See the notes and description here (tests of v1.4.71)  
https://github.com/rgleason/ocpn_draw_pi/releases/tag/v1.4.71

**Comment by jongough** [comment]
This is sort of by design. Don't forget the EBL moves with the boat so the end point moves as well. The EBL itself keeps the length and direction and updates the end point based on the start point. 

If you detach the start point you can then update the end point by typing or copy/paste then you have to attach the start point to the boat again. This will recalculate the length and angle based on the current position of the end point and the boat.

Hope this makes sense.

Jon

**Comment by rgleason** [comment]
Yes. 
Ok, maybe there should be a message after someone tries to paste that way? just when the action will not work.

**Comment by jongough** [comment]
OD 1.5.9 does show a message for EBL's warning about trying to update the lat/lon when centred on the boat.

**Comment by rgleason** [comment]
Ok, I'll try it out Jon.   I had written this
http://www.cruisersforum.com/forums/f134/odraw-1-5-beta-201521.html
Regarding trying to Paste Lat/Long into EBL Properties,
I had some other thoughts. When an EBL is set to Move with the boat and/or maintain a set angle from the boat centerline, then the Lat/Long field should be greyed out, such that a paste cannot be done. Also when a paste is allowed or permitted the Lat/Long field should be greyed or something so that it cannot be pasted to. I also believe that Copy and Copy Lat/Long should always be permitted. Is that clear enough?

I guess I'll stick to github dialog for this.

**Comment by rgleason** [comment]
jon,  I git pulled upstream master_1.5  and compiled.   It compiled 1.5.7 is this correct?
You say 1.5.9. 
v1.5.7  does not allow me to edit or copy lat/lon  text points, boundary pts, ebl etc at all.
v1.5.7 does import csv in the Temp Layer button (pick csv or all), and from the  Layers > Import gpx > change to "All".
v1.5.7 does not work and crashes O when  OD Points TAB > Import csc    and when Paths TAB > Import csv is picked.

What have I got wrong?

**Comment by rgleason** [comment]
now v1.5.12,  import csv works in all 3 instances.
copy lat/long does not work when the lat long gets greyed out. I think it should still allow copy.

Also the boundary points lat long etc get greyed out, in fact everything gets greyed out for some reason and you cannot paste lat long to anything, don't know why that is happening.  It happens after I successfully paste lat long somewhere.  

Other than that iit seems better, except, sometimes (fairly often) The object icons go black and I can't switch from the object to another. I have to close it and open the odraw icons then they get colored and I can pick.

It needs more testing I think. This was just a short session.

**Comment by jongough** [comment]
Fixed this issue and another on restart. Current patch is 1.5.14. 
I have not seen the 'black' icons on my test win 10 (under QEMU/KVM), but I am not using OpenGL. I will have to see if I can get my win 7 system running for that under VirtualBox.

Testing is the name of the game, this is a beta after all.

**Comment by rgleason** [comment]
Thanks Jon, not sure when I get a chance to test it. Going to varnish and get boat in water. Sometime this weekend though.

**Comment by rgleason** [comment]
Jon,
I've git pulled branch master_1.5 and compiled.  v 1.5.14  
Paste lat/lon and Copy lat/lon  are working as expected now.
One small quibble is the at we cannot copy lat/lon  for EBL.
I have also added this plugin version to releases [here]([https://github.com/rgleason/ocpn_draw_pi/releases/tag/v1.5.14beta]

**Comment by rgleason** [comment]
I guess the answer is now that we cannot change EBL lat/lon, however it would be possible to Copy EBL lat/lon if there was a purpose to that?

**Comment by jongough** [comment]
Rick,
   The EBL is really defined as a length and direction from a starting point, the default being the boat. The ODPoints that are used are to enable moving the end points to a user selected location, which really translates into a length and direction. If you fix the end point, i.e. it does not move with the boat (a check box is available for this in the properties) then the end point lat/lon is stable and does not change, this allows the user to then input the lat/lon they wish. If they then allow the end point to move, uncheck the check box, it will use the new lat/lon as the starting point for the EBL.

   Copying the lat/lon of a moving point would probably not give you the answer you were hoping for. As the end point changes as the boat moves and rotates, the real life probability of getting the lat/lon you thought you would is unlikely.

   The way of showing that the lat/lon is changing is by making these fields read only, i.e. you cannot interact with them in any way, so there is no way to get the event for copying them. This is a restriction on the current implementation of wxWidgets.

   I am currently working on 1.5.16 to allow Text Points to be imported through the CSV. Hopefully this will be done soon.

**Comment by rgleason** [comment]
Good explanation. Now I realize the way to do this is through the check box. I am going to close this.
