### ISSUE TITLE
Additions to Plugin API

### ISSUE THREAD

**Issue by jongough** [jongough/ocpn_draw_pi#4]
Dave,
   Currently there is a toSDDM_PlugIn declaration in ocpn_plugin.h which was added in 1.11 of the api, can you add fromDDM_PlugIn in the same way?

Thanks
Jon

**Comment by rgleason** [comment]
Messages in the issues section are sent to those who are "watching" the repository. Just as with opencpn

**Comment by jongough** [comment]
Dave,
   I would like to intercept the right mouse button click on the toolbar to allow me to change some settings (avoid adding more icons to the toolbar). Currently when right clicking it shows a popup with 'Visible buttons' in it, I would like to add another line to this, if the click occurs on my icon, so that I can change what the button is used for and the icon it displays. Is it possible to add another toolbar callback, but this time for the right mouse?

   Also, when the 'Visible buttons' is clicked it shows a list of visible toolbar icons. Currently there is no way that a plugin can modify this list to add/remove itself from the list. Can a callback be provided to do this?

Jon

**Comment by jongough** [comment]
Work around implemented for the 'right click' on the toolbar. Left click tool bar and select tool via round robin right clicking to change the tool before first use.
