### ISSUE TITLE
Win:  Boundary not showing

### ISSUE THREAD

**Issue by rgleason** [jongough/ocpn_draw_pi#417]
Jon, I was going to try testing for the timer interrupt. Downloaded the most recent O and compiled it, and tried Ocpn_draw on "Master"

I found that ocpn_draw objects were not displaying for some reason.
I removed everthing from manager and created a boundary. I could hover over the boundary and the yellow popups for the points came up. In the Draw manager I can see the new object, but not the boundary lines or the vertices points.

![Screenshot (654)](https://user-images.githubusercontent.com/2363959/78451272-a3757080-7652-11ea-9e50-84d585982057.png)

Suggest you wait until timer issue is resolved.
I don't see a crash due to timers on Windows, but maybe this is part of the problem?

**Comment by rgleason** [comment]
Same thing happens on an underpowered Virtualbox Ubuntu 18.04 with O about 1 week old.  Will pull and compile next.

**Comment by jongough** [comment]
Try without OpenGL. I noticed this the other day when doing some of the testing. I will look into it.

**Comment by rgleason** [comment]
Yes, turning off OpenGL fixes the problem! In windows and with opengl off when I uninstall the "enabledd" Ocpn_Draw, there is a screen redraw and the Plugin List Structure or framework shows for a moment, then Opencpn crashes.  

Tried the same in Ubuntu and the boundaries show.  Also tried disabling the plugin in Ubuntu and then uninstalling, this time Opencpn crashed, which I foundd to be unexpected.

**Comment by jongough** [comment]
Fixed, with patch 1.6.49, the opengl flag was not set so OD did not build with OpenGL, it now does. Can you give this version a go (it will be in my cloudsmith soon, or just pull the latest commit)?

**Comment by rgleason** [comment]
I have patch 1.6.51 which seems to  fix it.
I tried using the Custom catalog and putting in the URL to your cloudsmith for msvc and it was unclear to me if it installed.

So then I simply downloaded the exe and installed it and it seems to be working now with accelerated opengl graphics.  Thanks.

**Comment by jongough** [comment]
I am currently submitting changes to the master catalog. I have not used the custom one for a while, but with the repository name changes it probably isn't working. Will have to look into that.

**Comment by rgleason** [comment]
Jon, I found that Custom URL works, but it must be the cloudsmith url to the xml metadata file!
