### ISSUE TITLE
Cannot compile with VS2017 or VS2019

### ISSUE THREAD

**Issue by transmitterdan** [jongough/ocpn_draw_pi#418]
Jon,

I get a compiler error under VS2017/19:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2593	'operator =' is ambiguous	ocpn_draw_pi	E:\storage\transmitterdan\ocpn_draw_pi\extsrc\json-schema-validator\json-validator.cpp	387	
```

**Comment by rgleason** [comment]
Current Jon Gough Master
It built for Windows, with a little complaining about json validator
Maybe just building it is easier than using the cloudsmith tarballs for quick testing.

 ```
 tinyxmlerror.cpp
C:\Users\Rick\Documents\GitHub\ocpn_draw_pi\extsrc\json-schema-validator\json-validator.cpp(426): w
arning C4244: 'argument': conversion from 'T' to 'double', possible loss of data [C:\Users\Rick\Doc
uments\GitHub\ocpn_draw_pi\build\ocpn_draw_pi.vcxproj]
          with
          [
              T=__int64
          ]
  C:\Users\Rick\Documents\GitHub\ocpn_draw_pi\extsrc\json-schema-validator\json-validator.cpp(422):
   note: while compiling class template member function 'void `anonymous-namespace'::numeric<__int6
  4>::validate(const nlohmann::json &,nlohmann::json_schema::basic_error_handler &) const'
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\t
  ype_traits(616): note: see reference to class template instantiation '`anonymous-namespace'::nume
  ric<__int64>' being compiled (compiling source file C:\Users\Rick\Documents\GitHub\ocpn_draw_pi\e
  xtsrc\json-schema-validator\json-validator.cpp)
```

**Comment by jongough** [comment]
I am using VS2017, I don't have VS2019 installed as last time I tried it I had all sorts of problems getting it to actually run the compilation, so I reset my VM and just use 2017. Can you try with just 2017 without 2019 installed? Sometimes MSVS tries to be too clever and forces you to code in VS specific ways which is not helpful. I also don't get any issues with the line you have pointed out, my first line with a warning is the same as Ricks, 426, about a conversion from T to 'double'.

**Comment by transmitterdan** [comment]
I have some problem with my system.  It uses Windows Insider build so that may be the issue. Closing....

**Comment by jongough** [comment]
You can use the cloudsmith repository which has the latest version of OD available for multiple platforms. There are all the files there for the Plugin Manager installation using tarballs, but there are also installation packages, in your case 'exe' files that can be used. The may be an alternative to you building these yourself. All the packages are in my alpha repository which you will find here:
https://cloudsmith.io/~jon-gough/repos/ocpn_draw_pi-alpha/packages/?q=
If you want the xml file to use in the 'Custom' box of the Plugin Manger put *xml in the search box, if you want installables then put *exe, this will limit the number of files show to those that may be of interest. You then just have to pick the version you want.
