### ISSUE TITLE
API for programmatically drawing objects

### ISSUE THREAD

**Issue by utommo** [jongough/ocpn_draw_pi#439]
Hi Jon,

I'm writing this to you on behalf of a research group I'm part of at the Technical University of Denmark. We've been looking into using OpenCPN and the draw plugin to help us visualise various components of our research.

Is it possible to programmatically draw objects through external software? From what I can tell there are various importable objects of different formats (which we could write parsers for), but it seems these are only importable through the interface.

We also have a few more ideas and requests, which we wouldn't mind discussing. We're very interested in supporting the OpenCPN project in general and have the possibility of reimbursing for the assistance. Feel free to drop me an email at tthen [at] elektro.dtu.dk 

I apologise if this is the incorrect channel to perform this kind of outreach. But I was unable to find any other means of contact.

**Comment by jongough** [comment]
There is an API for ODraw which can use JSON or a binary API to allow creation and deletion of drawing objects. To see what is available and how to use it look at the ODAPI.cpp file. If you want an example of using the API then look at testplugin_pi (the plugin I use for testing the api) [https://github.com/jongough/testplugin_pi](https://github.com/jongough/testplugin_pi). This plugin is currently being used to help create the new way of building plugins, so the cmake process is changing quite a bit but the code is stable

**Comment by jongough** [comment]
Can this be closed?

**Comment by utommo** [comment]
Yes. Thank you very much for you help.
