### ISSUE TITLE
Only drawn when OpenGL is OFF

### ISSUE THREAD

**Issue by dominig** [jongough/ocpn_draw_pi#459]
I rebuilt Draw yesterday night and it only draw when OpenGL is OFF.
Is that a known issue ?

**Comment by rgleason** [comment]
I don't recall this being an issue.

**Comment by dominig** [comment]
I thought that is used to work in the past but it does do it now.
A short video showing the behaviour can be found here.
https://youtu.be/0fpbqcMSak8

**Comment by jongough** [comment]
This has been fixed with OD 1.8.4.0 which was put into master 4 days ago. Caused by a misconfiguration in the build environment.

**Comment by dominig** [comment]
Thanks. Last release fixes the issue.
