### ISSUE TITLE
Need  ODText.h for textpoint compile

### ISSUE THREAD

**Issue by rgleason** [jongough/ocpn_draw_pi#46]
"C:\Data-Dart\Up-Soft\Navigation\o-plugin\j-ocpn_draw_pi\build\ALL_BUILD.vcxproj" (default target)
(1) ->
"C:\Data-Dart\Up-Soft\Navigation\o-plugin\j-ocpn_draw_pi\build\ocpn_draw_pi.vcxproj" (default targe
t) (3) ->
(ClCompile target) ->
  C:\Data-Dart\Up-Soft\Navigation\o-plugin\j-ocpn_draw_pi\src\TextPoint.cpp(37): fatal error C1083:
 Cannot open include file: 'ODText.h': No such file or directory [C:\Data-Dart\Up-Soft\Navigation\o
-plugin\j-ocpn_draw_pi\build\ocpn_draw_pi.vcxproj]

    13 Warning(s)
    1 Error(s)

**Comment by jongough** [comment]
Sorry, I was in the process of updating the code and missed putting this up as it was a name change and I obviously missed that in the code. Will correct it ASAP.

**Comment by rgleason** [comment]
Done
