### ISSUE TITLE
Extend Ocpn_draw and include

### ISSUE THREAD

**Issue by rgleason** [jongough/ocpn_draw_pi#490]
https://github.com/OpenCPN/OpenCPN/discussions/2450

**Comment by jongough** [comment]
OD could do Route and Waypoint, but this would require Dave to make the decision. There is no point in having two ways of doing the same task as it would just waste developer resources. The current design of OD is based on OCPN Route and Waypoint code but modified to make it more generic hence Path and Points which are then specialised into the different objects that OD current handles. It would take little to generate Route and Waypoints, but the effort would be in handling autopilots and making the system resource efficient and fast enough to be really useful.

**Comment by rgleason** [comment]
Good point about AP.  Is that possible?

**Comment by jongough** [comment]
Anything is possible, but it would/may require further OCPN API's to do it. Again, unless Dave wants to have OD reintegrated into OCPN or offload the Route and Waypoint processing and all the associated funtions, i.e. AP, then there is little point in starting the process. 

That said, if someone wants to play with OD and OCPN to get this functionality working they only need to have the two git repositories and create a new branch and work on those. That is what I did for OD when splitting it off from OCPN.

**Comment by rgleason** [comment]
Thanks Jon.

**Comment by rgleason** [comment]
Maybe I shoild close this.
