### ISSUE TITLE
FS#920 - UI UNITS Setting measurement units 

### ISSUE THREAD

**Issue by rgleason** [jongough/ocpn_draw_pi#493]
https://opencpn.org/flyspray/index.php?do=details&task_id=920

Would Ocpn_Draw be a logical place to provide a single place to set UNITS?
It is not going to happen in Opencpn as that is not it's core function.
Ocpn_Draw is kind of at the center of many plugins and already has ODAPI

**Comment by jongough** [comment]
I thought most of this was available in the standard settings dialog. For OD to do it there would need to be new, I think, OCPN API entries that would allow the settings to be changed. This seems rather a round about way of achieving the goal. I think it may be better to just modify OCPN to include the missing settings and ensure they are used (the last bit would have to be done even if OD presented the settings page).

**Comment by rgleason** [comment]
I don't sse much about UNITS in the API,  chartscale and perhaps depth units, and cursor position.

**Comment by jongough** [comment]
The only thing that is assumed and a bit inconsistent is the date format. It should be set on the 'Units' tab of the settings dialog and then should be propagated through OCPN and to the plugins. Time is normally expressed in the 24hr way and 'may' be also in UTC (or some variant), so perhaps this should/could be settable, but the system clock settings can be used for this, but....
