### ISSUE TITLE
Listing Panel Icon

### ISSUE THREAD

**Issue by rgleason** [jongough/ocpn_draw_pi#494]
Jon, I would like to improve the PIM listing panel icon. I hope you agree.
I have attached two files called od_panel.svg and od_panel.png
These are using your design as a basis, but just change the background and tools settings
![od_panel](https://user-images.githubusercontent.com/2363959/142644926-99bf3a04-2b17-42ac-a0be-ffa212078299.png)
[od_panel.svg.txt](https://github.com/jongough/ocpn_draw_pi/files/7571088/od_panel.svg.txt)

Thanks

**Comment by jongough** [comment]
Probably best if you make the change in a branch of git and create a pull request. Then there is a track of the changes. What was the issue with the current icon and what did you change to make it 'better'?

**Comment by rgleason** [comment]
Ok,  will make a PR, but I don't do binary changes to images. Have not learned how to do that, so I will need to make some changes so that the od_panel.png is read.  Haven't looked at the code yet.  The reason for this is better visibility because it is a basically a good icon.

I changed the background to 10% to match the overall background of the listing_panel  so they've been calling it a panel icon.

Also increased the blacks in the tools to something a notch higher for better visibility.

**Comment by rgleason** [comment]
Jon, I started to make a PR and have gotten into it, but you are using the toggle icon for the Listing Panel Icon. That normally does not work very well due to the different backgrounds, etc.

I have decided not to do anything about this and let you do it if you want. I just don't think the  Ocpn_Draw  Listing Panel Icon is optimal and I have provided one that would be better in my opinion, but I don't want to mess with your code to create a separate process to load the icon into the listing panel.

**Comment by rgleason** [comment]
If it were my plugin I would have a background of 10% grey to match the listing panel background, and have the drawing be about 85% (darker) so that it is simply the drawing part darker, overlaid on the listing panel background.

It will read more consistently with the other plugins and be easier to  pick out the icon.

**Comment by rgleason** [comment]
Here is what it looks like now. It is actually quite indeciferable, and yet the graphics of the tool itself are quite good!
![Listing-Panel](https://user-images.githubusercontent.com/2363959/142713183-5a81b996-a13f-4ed0-a92f-469b154432b7.png)

**Comment by jongough** [comment]
I have updated the icon for the plugin properties panel to have a transparent background and a slightly darker foreground. This will be in the next update.

**Comment by rgleason** [comment]
Thanks very much Jon.

**Comment by rgleason** [comment]
BTW for statusbar I made an  SB and an indication of an abstracted grey statusbar underneath

**Comment by rgleason** [comment]
I think transparent background is a very good idea. I had not thought of that.
