### ISSUE TITLE
High Res Screens  and Icons and draw pencil

### ISSUE THREAD

**Issue by rgleason** [jongough/ocpn_draw_pi#496]
Jon on my High res screen the draw icons shrink too much.
Bdbcat had to make some adjustments in Opencpn for high res screens so we could get reasonable sized icons.
Also for a certain resolution of screen he reverts the cursor back to normal because the pencil is impossible to see.
I need both of these things in Ocpn_Draw.
![Screenshot (129)](https://user-images.githubusercontent.com/2363959/145425632-d70b664c-58ef-48de-9480-61fe08f51b69.png)

For these changes you can see them in OpenCPN here
https://github.com/OpenCPN/OpenCPN/issues/2469
https://github.com/OpenCPN/OpenCPN/commit/16ae5b70ecdc724506edb499a225a02326530c82

For the icons I have to change the settings   options > User Interface   check enable scaled graphics interface, or set User Interface scale factor at 5

**Comment by jongough** [comment]
The cursors used by OD are the ones supplied by OCPN. OD does change the cursor depending on what the user is doing, but they are still the cursors supplied by OCPN though the "GetIcon_PlugIn" and "SetCursor_PlugIn" API calls. So I am not sure what you expect OD to do with this. It is a problem for OCPN.

**Comment by jongough** [comment]
I hope any change made by OCPN is reflected in the calls by plugins for the cursor icons.

**Comment by rgleason** [comment]
Ocpn_Draw 1.8.20 issued to Beta Catalog
