### ISSUE TITLE
RFE: Create a Runway, Corridor or Passageway...PIL does not fit the bill

### ISSUE THREAD

**Issue by rgleason** [jongough/ocpn_draw_pi#499]
Jon, see this request
https://www.cruisersforum.com/forums/f134/corridor-passageway-259315.html#post3545364

Is there a way to repurpose PIL to work or create a slightly different object?

**Comment by jongough** [comment]
The PIL should work, but I found an issue with moving both the start and end points and then trying to select the PIL again. Being based on an EBL most of it was working as needed. I have responded to the post you pointed too. Just not sure if the PIL with two lines that extend to the edge of the OCPN window is what the person wants, but....

**Comment by rgleason** [comment]
Thanks Jon
