### ISSUE TITLE
German Umlaut

### ISSUE THREAD

**Issue by nocheinpeter** [jongough/ocpn_draw_pi#530]
.gpx files containing german umlaut in filename / title cannot be loadad under android
See attached file (Upload replaced the ä by au)
[Sperrgebiet Kampfmittelräumung.gpx.txt](https://github.com/jongough/ocpn_draw_pi/files/12138044/Sperrgebiet.Kampfmittelraumung.gpx.txt)

**Comment by nocheinpeter** [comment]
Add now ZIP with original filename.
[Example.zip](https://github.com/jongough/ocpn_draw_pi/files/12138046/Example.zip)

German umlauts are ä, ö, ü 
ä = au
ö = oe
ü = ue

maybe ß = ss won't work, too.

**Comment by jongough** [comment]
I have just done a trial on a Ubuntu machine (setup of English Australian) and it imported both files. The file manager shows:
![image](https://github.com/jongough/ocpn_draw_pi/assets/2803240/5b2c9f50-3521-45ee-b4f5-c0ca317aad45)
and both give the same looking boundary in OCPN:
![image](https://github.com/jongough/ocpn_draw_pi/assets/2803240/24710c71-b912-47a4-bd0c-11f13b93a23f)
I am not really sure what android shows when it displays umlauts in its native filemanager, I presume using the German character set (inlcuding umlauts).

Have you tried the same test on OCPN using a route that has a name with umlauts in it, then exporting and re-importing to see if OCPN handles this correctly? Also, in OCPN/Options/User Interface, what language do you have set?

**Comment by nocheinpeter** [comment]
I use german language settings. 
The file manager works with umlaut.
I created the file on windows and then imported it on android.
Import route file into android opencpn with umlaut created on windows does not work either.

[Test German Umlaut ä.zip](https://github.com/jongough/ocpn_draw_pi/files/12138134/Test.German.Umlaut.a.zip)

**Comment by nocheinpeter** [comment]
When I try to export a route on android with an umlaut in the filename, the file is empty.

**Comment by jongough** [comment]
I have just done an import of the route on Ubuntu (desktop) and it works fine. So it would appear to be an issue with android and its handling of national characters. As both route and boundaries have the same issue could you please raise an issue on OCPN about the 'route' not being imported correctly. That development stream has more people active on it from Europe and who can look at this type of issue more easily. Both Draw and OCPN use similar code for importing/exporting files and therefore if there is a fix for OCPN it can be fairly easily, I hope, implemented into Draw.

Sorry for the runaround.

**Comment by nocheinpeter** [comment]
No big thing. If people know, replacing nation characters is easy. I will forward the bug to openCPN.

**Comment by jongough** [comment]
Thanks, I will try to keep an eye out for what happens and implement any change if I can.

**Comment by nocheinpeter** [comment]
Reported at [https://github.com/OpenCPN/OpenCPN/issues/3363](https://github.com/OpenCPN/OpenCPN/issues/3363)
