### ISSUE TITLE
Segfault with wxgtk 3.2?

### ISSUE THREAD

**Issue by hreuver0183** [jongough/ocpn_draw_pi#533]
With Debian 12 (Bookworm) I find opencpn segfaulting on ocpn_draw.
According to the backtrace there seems to be some issue with wxgtk-3.2.
(OpenCPN 5.8.4, Ocpn_draw 1.8.28-2).

There is  a ocpn_draw_pi-1.8.28.2-debian-x86_64-12-bookworm.xml (OpenCPN - Plugins - metadata). The segfault is with a self-compiled plugin (as Debian 12 Bookworm seems not supported due to a lack of a downloadable plugin in either master or beta).

(Included opencpn.log, opencpn.conf and backtrace)
[segv_wxgtk_3.2.zip](https://github.com/jongough/ocpn_draw_pi/files/12507419/segv_wxgtk_3.2.zip)

**Comment by rgleason** [comment]
What?  Would you mind looking for weather_routing, weatherfax, climatology or celestial_navigation and trying those please?

**Comment by hreuver0183** [comment]
<off-topic>
Celestial navigation shows no error, but I don't know how to test.
Climatology seems to work as expected (but the feedback during the downloading is more or less "not available") I had no current, I did have wind speed.
Both had plugind available.

Weather_routing and  weatherfax I can test, but there is no plugin, I'll have to compile first.
</off-topic>

**Comment by rgleason** [comment]
[off-topic]

What OS version Bookworm are you using.

You should not have to compile these they should be available in Plugin Manager (PIM) via Options > Plugins  Install and Enable.
During installation you need to be connected to internet or satelite to download the data files 7.8mb.
For example the metadara for climatology is:
- climatology_pi-1.5.5.10-debian-arm64-12-bookworm-arm64.xml
- climatology_pi-1.5.5.10-debian-arm64-12-bookworm-armhf.xml
- climatology_pi-1.5.5.10-debian-arm64-12-bookworm-x86_64.xml

Celestial Nav
Weather_routing
Weatherfax
all have similar files available through PIM so you should be able to access them from PIM, download them. install and enable them.  In fact the most of the Testplugin Frontend Templated plugins should be readily available from PIM and install.

We need to know if this system is working for bookworm.

**Comment by hreuver0183** [comment]
[off topic]
Currently the regular plugins include, bookworm / x86_64:
- weatherrouting
- weatherfax
- climatology
- vdr
- objsearch 
- others i did not test

The most visible plugins not available:
- pypilot
- o-charts
- ocpn_draw

This means that extra plugins did become available after your action.
There is however a reason to want to compile my own plugins.

Basically the reason is that some plugins are still missing for debian 12/x86_64.
The other reason is, I don't expect you to maintain debian 12/arm64.

 (The RPI4 is obsolete, there is no supported current arm64 platform. The Odroid N2 is only slightly less obsolete than the RPI4 and the RK3588 system who are significantly faster are still not supported. Bookworm works for the Odroid N2 but it will be a niche platform.)

**Comment by rgleason** [comment]
What about watchdog ?
