### ISSUE TITLE
about circle_pi

### ISSUE THREAD

**Issue by seaside82** [jongough/ocpn_draw_pi#6]
hi Jon,
Lets me i indroduce me, i try and i wrote an issue for your plugin about a week ago when i was been in Bristol in u.k., i am an officer has been working at sea since 2002. Now i have been on Jorf Lasfar Port in Morocco by the ship https://www.marinetraffic.com/en/ais/details/ships/shipid:408045/mmsi:351653000/vessel:MUKARNAS .
Nearly 3 months i have been working on many plugins then i decide to make a my first plugin which is i calling circle_pi. Drawing a circle on the screen. i was going to add a picture here but my internet too slow could not open some another pages (due to this reason i broke my phone which i used to connect to life then now i use frends nets, its too slow, it was before also).

Nearly a month a working on this circle_pi. 3 times had formatted to my computer because some problems are happens when i install wxWidgets. How is it change somethings i dont know but its different size executable files occurs before install and and after install wxWidgets. Before install wxWidgets i can compile any plugin and these was work but these never works when i compile same files after then install wxWidgets.
## Could you help me, what is wrong here. Actually the parts of 

```
    int n=0,nleg=0;
    double lati, loni;
    double ESheading=-approach;
    for ( int x = 1; x<= 360; x++ ) { //Loop over the legs
        wxString wpt_title;
        n++;
        destRhumb(lat1, lon1, ESheading,leg_distancex, &lati, &loni);
        {
            ESheading-=0.0;
            nleg++;
            if (write_file){Addpoint(Route,wxString::Format(wxT("%f"),lati),wxString::Format(wxT("%f"),loni), wpt_title ,_T("empty"),_T("WPT"));}
            }

         ESheading=ESheading + 1;
```

---

circlegui_impl.cpp file.

it was SAR_pi before then i change this part for drawing a circle then it has work but when i change and configurate its files for user interface then i has not work.
Could you check and tell me, what is wrong here, this is my first plugin and i am not a programmer. just i try to learn and share with people for benefits, all of us.

Thanks in advance. hope i can sent this mail in spite of too slow net.
![screenshot from 2015-03-22 01 01 27](https://cloud.githubusercontent.com/assets/6827147/6767362/8c210e92-d023-11e4-8903-ef41e4dd0735.png)

**Comment by jongough** [comment]
Hi,
   I have just found your code on github and had a quick look. It would appear that you are reusing some of the code in the mainline, i.e. RoutePoint to base your code on. My plugin is replacing RoutePoint with OCPNPoint to try and make it more generic. The idea that Dave wanted me to pursue was to create a general purpose drawing plugin, and your would appear to fit into that category as well. I have a working, just, version of this now, but it does require the latest OpenCPN from git as it makes use of some new plugin api calls.

   I had a working version of Boundaries in the mainline which I wanted merging, but I was persuaded to try it as a plugin. I am still working on openGL and some of the mouse functionality. You will find in the mainline git that waypoints now have range rings, which may be what you are trying to do with part of your plugin. I will be pulling this code into my plugin soon.

   So, it may be worth merging your work into this one in the near future, but I want to stabilise it a bit more before I try that.

   What version of wxWidgets are you using and what operating system are you building this plugin on? I am currently using Linux for my development, then compiling under windows 7 as a test. But I do not yet have a windows system I can run the plugin on. I should get to that soon.

Jon

**Comment by seaside82** [comment]
Hi Jon,
Is is possible to chatting with you on some platforms or a mail adressess is possible? All before i explain, happens on Pardus (my operating system) which has been based on debian, happens both of releases distrubution Pardus 1.0 wheezy and Pardus 3.0 rc2 jessie.

i install wxFormBuilder_v3.5.0-beta-source and wxWidgets-3.0.2 both of this os (Pardus). 

The other problem last night last and 4th times i formatted again my laptop. Now i use Pardus 3.0 jessie (before iw was rc, now use latest stabil jessie). Why i explain this because on this distro repos does not include libwxgtk2.8-dev libwxgtk2.8-dev wx2.8-headers wx2.8-headers these files it include 3.0 version all of these packages.  So i installed these packages version 3.0. when i compile OpenCPN it doesnt work. 

I think i can found from some another repos of this packages with 2.8 version. But that time may be possible to wrong somethings on my operating system, what is your opinion.

Thanks for your help me
Ömer Çakir

**Comment by seaside82** [comment]
Hi,
Sorry i fix my problem about compiling opencpn its my fault. I found. i forget install after then compiling it and i was start it between make and make install directly, now its ok, opencpn works but i dont know other problems about wxwidget which version i have to be use.

Thank you.

**Comment by jongough** [comment]
Glad to hear you have it working OK now.

The official position is to use xwWidgets 2.8, however, I am using wxWidgets 3.0 and it is working OK. If there is a problem then you need to be able to use the 2.8 version or your problem may be rejected.

**Comment by seaside82** [comment]
Hi Jon

Pls look https://github.com/OpenCPN/OpenCPN/issues/261

**Comment by rgleason** [comment]
Looks to me like he is interested in creating a drawing tool for use with SAR_pi to aid in search.
Some combination of SAR_pi, tracking on, with a drawing tool to plan the operation. I suppose wind, current vectors would also be appropriate factors to show.

**Comment by jongough** [comment]
Can he use the current waypoint/routepoint code that allows for range rings to do what he needs at the moment? I think the boundary stuff may help him, but I need to get it into beta quality before I am willing to integrate too much else. I think the plugin is getting close to beta, just need the SetCursor to implented into the mainline.

**Comment by rgleason** [comment]
seaside82  -Opencpn v4.2 is now using wxWidgets 3.0.2
