### ISSUE TITLE
Fresh clone cmake breaks

### ISSUE THREAD

**Issue by seandepagnier** [jongough/ocpn_draw_pi#72]
CMake Error at CMakeLists.txt:229 (ADD_LIBRARY):
  Cannot find source file:

    src/BoundaryPoint.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

CMake Error: CMake can not determine linker language for target: ocpn_draw_pi
CMake Error: Cannot determine link language for target "ocpn_draw_pi".
-- Generating done
-- Build files have been written to: /home/sean/build/plugins/ocpn_draw_pi/build

**Comment by jongough** [comment]
I have put up the missing files. It should work now.
